# Generated by Django 5.2.7 on 2026-07-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='escudo',
            field=models.CharField(blank=True, default='/assets/escudos/default.png', max_length=255, null=True),
        ),
    ]
