# Generated by Django 5.2.7 on 2026-07-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_equipo_escudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='escudos/'),
        ),
    ]
