# Generated by Django 6.0.4 on 2026-04-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO socios_socio (nombre, telefono, direccion, email) VALUES "
            "('Juan Pérez', '1144556677', 'Av. Córdoba 1234, CABA', 'juan.perez@gmail.com'), "
            "('María González', '1167891234', 'Calle Falsa 456, Rosario', 'maria.gonzalez@hotmail.com'), "
            "('Carlos López', '1133445566', 'Av. San Martín 789, Mendoza', 'carlos.lopez@yahoo.com'), "
            "('Ana Torres', '1122334455', 'Mitre 321, La Plata', 'ana.torres@gmail.com'), "
            "('Lucía Fernández', '1198765432', 'Belgrano 987, Córdoba', 'lucia.fernandez@gmail.com'), "
            "('Martín Ramírez', '1177889900', 'Av. Rivadavia 4321, CABA', 'martin.ramirez@gmail.com'), "
            "('Sofía Castro', '1100112233', 'Urquiza 1111, Mar del Plata', 'sofia.castro@gmail.com'), "
            "('Diego Sosa', '1188997766', 'Alsina 654, Bahía Blanca', 'diego.sosa@gmail.com'), "
            "('Valentina Díaz', '1155667788', 'Av. Colon 2020, Salta', 'valentina.diaz@gmail.com'), "
            "('Federico Ruiz', '1133221100', 'San Juan 3030, Tucumán', 'federico.ruiz@gmail.com');"
        ),
    ]
