# Generated by Django 5.2.7 on 2026-06-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_auto_20260426_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='division',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='socio',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
