# Generated by Django 6.0.6 on 2026-08-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_producto_descripcion_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='talle',
        ),
    ]
