# Generated by Django 6.0.6 on 2026-08-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_remove_producto_talle'),
        ('talles', '0002_auto_20260426_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.CreateModel(
            name='TalleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talles_disponibles', to='producto.producto')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talles.talle')),
            ],
            options={
                'verbose_name': 'Talle Stock',
                'verbose_name_plural': 'Talles Stock',
                'unique_together': {('producto', 'talle')},
            },
        ),
    ]
