# Generated by Django 6.0.4 on 2026-04-26 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_auto_20260426_2245'),
        ('socios', '0002_auto_20260426_2222'),
        ('talles', '0002_auto_20260426_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talles.talle')),
            ],
        ),
    ]
