# Generated by Django 6.0.4 on 2026-05-06 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20260426_2247'),
        ('compras', '0002_auto_20260426_2258'),
    ]

    operations = [
    ]
