# Generated by Django 5.2.7 on 2026-07-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_merge_0002_auto_20260426_2247_0002_auto_20260426_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
