# Generated by Django 6.0.6 on 2026-08-09 21:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_compra_cantidad_alter_compra_precio'),
        ('producto', '0004_remove_producto_talle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='precio',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='talle',
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='detalles_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('compra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
