# Generated by Django 6.0.6 on 2026-08-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_rename_precio_compra_total_remove_compra_cantidad_and_more'),
        ('producto', '0004_remove_producto_talle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detalles_compra',
            new_name='DetalleCompra',
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalles de Compras'},
        ),
        migrations.RenameField(
            model_name='detallecompra',
            old_name='compra_id',
            new_name='compra',
        ),
        migrations.RenameField(
            model_name='detallecompra',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
