# Generated by Django 6.0.6 on 2026-08-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_rename_detalles_compra_detallecompra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={},
        ),
    ]
