# Generated by Django 6.0.6 on 2026-08-11 21:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_detallecompra_precio_unitario'),
        ('talles', '0002_auto_20260426_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='talle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talles.talle'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
